### ISSUE TITLE
Add automated rendering from youtube input?

### ISSUE THREAD

**Issue by JamesKitching** [uzh-rpg/rpg_esim#15]
I am a hobbiest researcher with limited time;  i.e I have a full-time non-research job :-(. 

Could you enhance you simulator so that it could render continuously automatically from an online URL such as a youtube video or a video file / video stream?

I want to work on creating visual / augmented modelling of word understanding based on SLAM cotextual recognition of a small set of every important words.

See https://hemseye.org/wp/2018/08/26/hemseye-project-phase-1-shorter-presentation/

Further enhancments would be adding a sync / timestamp to integrate the video sound output.

Many thanks 

regards

James Kitching

**Comment by supitalp** [comment]
Hi,
This will not be possible, as the main goal of ESIM is to implement a tight coupling between the rendering engine and the event simulation, to ensure that the maximum pixel displacement between successive frames is below a threshold (say, 0.5 pixel). Details are in the [paper](http://rpg.ifi.uzh.ch/docs/CORL18_Rebecq.pdf).
Simulating events from successive frames streamed from YouTube would be possible, but there would be no guarantee that the simulated events are accurate since you would not be able to control the displacement between the received frames, therefore I would advise against it.

If you still want to do it, I would suggest not to use ESIM (which has heavy machinery designed to implement the guarantee mentioned above), but rather the simpler event simulator written in Python available [here](https://github.com/uzh-rpg/rpg_davis_simulator/blob/master/src/dvs_simulator_py/dvs_simulator.py#L36).
