### ISSUE TITLE
using ESIM  for object detection

### ISSUE THREAD

**Issue by germal** [uzh-rpg/rpg_esim#27]
Hi 
Could be possible to use ESIM to process realtime video  and use the events to make object recognition from drones performing trajectories at high speed ? 
Thanks !
Germal

**Comment by supitalp** [comment]
Hello,

Using an event camera to detect moving objects on drones is doable, yes (see here: http://rpg.ifi.uzh.ch/docs/RAL19_Falanga.pdf).

However, converting the frames from a standard camera to a virtual event stream (instead of using a real event camera) for this task does not seem like a good idea: you would essentially lose the advantages of event cameras since the frames would suffer from motion blur, under- over- exposure, etc.

While it would be possible to adapt ESIM to perform what you describe (see relevant simulation code here: https://github.com/uzh-rpg/rpg_esim/blob/master/event_camera_simulator/esim/src/event_simulator.cpp#L21), note that the simulated events would not be accurate since nothing guarantees that the optical flow between two frames in the video is small enough to yield accurate events.
